[package]
name = "oci-runitme-rs"
version = "0.1.0"
authors = ["Viktor Lazarev <taurus101v@gmail.com>"]

[dependencies]
reqwest = "0.8.8"
bzip2 = "0.3"
clap = "2.32"
error-chain = "0.12"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
tar = "0.4"
